Improve Javadoc generated by "Make Static" refactoring #1043
eclipse-jdt/eclipse.jdt.ui pull request #1084
Opened 2024-01-17 13:41 UTC by HeikoKlare

## What it does

This change improves the Javadoc generation behavior of the "Make Static" refactoring and aligns it with other refactorings such as "Change Method Signature". It ensures that generated parameter tags are inserted at proper positions within an existing Javadoc comment.
<s>This change improves the Javadoc generation behavior of the "Make Static" refactoring and aligns it with other refactorings such as "Change Method Signature". This includes (1) adding a "TODO" to added parameter tags and (2) inserting parameter tags at proper positions within an existing Javadoc comment.</s>
The tag for the parameter itself is added as the first parameter tag, following any author or version tags. The tags for potential type parameters are added as the last parameter tags, preceding any other tags than author or version.

The reused functionality from `ChangeMethodSignatureRefactoringContribution` is factored out to the `JavadocUtil` class.

Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1043

## How to test

The behavior can be reproduced by applying the "Make Static" refactoring to any method that when refactored requires a `this` parameter and has Javadoc into which the documentation for the added parameter has to be inserted. To see different flavors of the behavior, it's easiest to consider the regression test cases provided with this PR.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2024-01-17 14:42 UTC, HeikoKlare commented
Thank you for reviewing and merging all the polishing PRs for the "Make Static" refactoring, @jjohnstn!
This one will fix the Javadoc issue you have pointed to in the original feature PR: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/689#discussion_r1428535735
Together with #1085, every issue with the refactoring that I currently know about should be fixed (see also https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/689#issuecomment-1895849551).

2024-01-17 21:57 UTC, jjohnstn requested changes
Do not add the TODO description for any added parameter.  This won'tt flag anyone via warnings/etc. to fix it later.  If one creates a Javadoc comment on a method, it will create the parameter tags without any comment.  You should be consistent and do the same.

2024-01-18 21:16 UTC, jjohnstn commented
Hi @HeikoKlare I don't know about the other refactorings/proposals, but I do know if I create Javadoc for a method with parameters, it does not add TODO tags.  Similarly, if I add a new parameter and then hover over it to add documentation for it, it again does not create the TODO tag.  JavadocUtil.createParamTag() has a TODO note to eventually change to add a {@todo} tag which might make sense for some of the other cases.

2024-01-18 21:51 UTC, jjohnstn approved these changes

2024-01-18 21:51 UTC, merged

2024-01-19 07:43 UTC, HeikoKlare commented
Yes, almost every actions that introduced Javadoc tags does not add TODO tags. That's why I totally agree with you that this refactoring should not do it either and adapted the code accordingly.

> JavadocUtil.createParamTag() has a TODO note to eventually change to add a {@todo} tag which might make sense for some of the other cases.

Note that this TODO note is from 2004 and will probably not be addressed. The code does not as if there is any systematics behind using this utility method and adding the TODO description, but I guess it was an early-days idea of an implementor of a single refactoring to provide some kind of "TODO" for added javadoc tags but that has never been implemented properly. And now there are few places (exactly the two refactorings I mentioned) where this "TODO" description is added. Since no one complained so far, there is no real demand to change it. I just wanted to offer to unify this to have a more consistent behavior of the javadoc generation of all refactorings.