String support for if/else to switch cleanup
eclipse-jdt/eclipse.jdt.ui pull request #1514
Opened 2024-07-16 17:44 UTC by carstenartur

## What it does
Since Java 7 there is support for "switch" statement making use of "String" objects. The cleanup for that in eclipse jdt ui so far only supports primitive types like char, int and so on. 
I just want to see what is needed to add support for the cleanup to refactor if/else chains with String constant comparisons to switch statements as well.
It does not check the projects java version. Not sure if that makes sense any longer. Do we support java 6 today?
In an ideal world there should be at least to tests in a java 6 test configuration and a java 7 test configuration. The currently used "CleanUpTest12" seems to be somehow random.

## How to test

There is a single junit test so far. You can add testcases or use e.g. the jdt codebase for testing.

## Author checklist

- [ ] I have thoroughly tested my changes
- [x ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2024-07-16 19:29 UTC, jjohnstn commented
Thanks @carstenartur .  We just removed support for < Java 1.8 so JVM check is not needed.  Not sure about the history of why all of this is in CleanUpTest12, but it doesn't matter.

2024-07-16 19:37 UTC, jjohnstn requested changes
Looks good.  Just some minor nits.  I will merge when done.  BTW: I have marked this as Noteworthy.  Are you interested in adding a N&N entry or would you like me to do it?

2024-07-16 19:37 UTC, jjohnstn commented on org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchFixCore.java
> +						if(!"equals".equals(method.getName().getIdentifier())) return null; //$NON-NLS-1$
Minor nit.  Please stick with if-space-(

2024-07-16 19:37 UTC, jjohnstn commented on org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchFixCore.java
> +						if(arguments.size()!=1) return null;
same comment about if statement.  Please also add spaces around !=

2024-07-16 19:37 UTC, jjohnstn commented on org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchFixCore.java
> +//					if (!JavaModelUtil.is1d7OrHigher((IJavaProject)null))
Remove these two commented lines.

2024-07-17 09:31 UTC, carstenartur commented
Hi Jeff,
please go ahead and create a N&N entry if you feel like doing it.
Btw, should support for "enum" be added in this cleanup one day? Maybe it is pointless because everybody prefers "switch" beforehand when using enum anyway and so there is are no cases to cleanup but I'm not sure.

2024-07-17 14:53 UTC, carstenartur commented
I do not see how to check for an "enum". The approach used in the other cases does not work.

2024-07-17 20:27 UTC, jjohnstn approved these changes

2024-07-17 20:28 UTC, jjohnstn commented
Hi @carstenartur Thanks for the changes.  Enum support would be fine but as you mentioned, it is likely a user would have used a switch to begin with.  To find an enum, the ITypeBinding has an isEnum() method.  For an enum value, doing a resolveBinding() of the name will give an IVariableBinding which has isEnumConstant() method.

2024-07-17 20:30 UTC, merged

2024-07-17 20:31 UTC, jjohnstn commented
@carstenartur I'll do the N&N for 4.33 M2.