Explicitencoding
eclipse-jdt/eclipse.jdt.ui pull request #1631
Opened 2024-09-08 12:00 UTC by carstenartur

Port of "explicit encoding" cleanup from https://github.com/carstenartur/sandbox to eclipse

## What it does
Some java api has been designed originally without a strong focus on safety on usage of different charsets. Because of that apis have simple string parameters to determine the encoding to use or even a default encoding that is based on the environment settings. The situation has improved a lot and you should explicitly the charset. In doing so for type safety better switch to Charset class.

## How to test
Use the cleanup on one of the affected java apis.

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2024-09-09 07:13 UTC, carstenartur commented
@jjohnstn would it be acceptable to have a separat test project to hold junit5 based tests until they can be backported to the junit 4 standard jdt.ui complies to?

2024-09-09 07:24 UTC, akurtakov commented
Note that if you have separate project it would not be automatically executed by  Ibuilds unless you do the extra work to register it like done in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2322 .

2024-09-09 08:00 UTC, carstenartur commented
Ok, what is your advice, @akurtakov ?

2024-09-09 08:07 UTC, akurtakov commented
JUnit 5 can run junit 4 tests so migrating the suites to junit 5 suites should allow migrating tests to junit 5 one by one while in the same bundle.

2024-09-09 08:18 UTC, carstenartur commented
Ok, so you mean moving the tests to the usual test folder and add it to a suite?

It is a pity that this approach does not allow to add code coverage computation and clear splitting of test and supporting code. 

Fine with me. I need help for parts of the implementation anyway:
How to provide a Java 18 based test environment? 
How to remove different exceptions catched after applying the fix?

2024-09-17 01:53 UTC, jjohnstn commented
Hi @carstenartur The Java 18 stubs are something I have meant to look into.  The recipe for stubs did not work for me and I need to get some help from the IBM folks or Stephanne.

2024-09-17 02:03 UTC, jjohnstn requested changes
General comments.

1. new plug-ins need about.html files (added to sources as well) - won't matter if you move them to existing plug-ins
2. new plug-ins should be 1.0.0 rather than match platform 4.34 (jdt.ui and jdt.ui.tests for example are lower versions) - again moot if you move into existing test plug-ins
3. nearly all files including test sources and property files should have licensing headers (see other JDT plug-ins if in doubt)
4. plug-in name and provider name should be supplied by plugin.properties file - moot  when moved
5. remove commented out code bits unless they will be added at a later date
6. not sure about how this is added to Java Feature tab - there are Java 10 and 18 specific items but you only add Java 6 options and this appears after Java 5 and not between 5 and 7 (should it just be on or off in a different tab like code style?)
7. last encoding option has no preview changes (as far as I can see - single constant) and isn't very clear (is it needed or should it be defaulted)?
8. perhaps a little more description in feature option could help users to understanding what it is doing

2024-09-21 09:47 UTC, carstenartur commented
> JUnit 5 can run junit 4 tests so migrating the suites to junit 5 suites should allow migrating tests to junit 5 one by one while in the same bundle.

@akurtakov I have copied the tests to the usual project without backporting them to junit 4. They can be executed now if you start them explicitly but do not run as part of the junit 4 based jdt test suites.
Any suggestion to get rid of the need to port them back to junit 4?

2024-09-27 18:07 UTC, jjohnstn commented
Hi @carstenartur You should never do a merge commit in a PR.  You need to instead do a rebase on up to date master.  You need to locally do a hard reset to the commit before the merge, then do a rebase on top of up to date master, then do a force push to fix this.

2024-09-27 18:21 UTC, carstenartur commented
> Hi @carstenartur You should never do a merge commit in a PR.  You need to instead do a rebase on up to date master.  You need to locally do a hard reset to the commit before the merge, then do a rebase on top of up to date master, then do a force push to fix this.

Hi @jjohnstn, thanks for hint but I think I can simply solve it by choosing a "rebase update" in the web interface after the next change is merged to master. Dunno why it is not configured as default in jdts github setup. I would have done that beforehand but the webinterface of github does not allow it in case of a conflict it seems. So to solve one conflict that showed up with the libraries in one manifest file I had no choice at least as long as I solve the conflict in the web interface of github.
But it does not matter, I'm not in hurry. We can merge next year - currently I have no idea how to run Jave 18 based tests anyway.

2024-09-27 18:32 UTC, carstenartur commented
> Hi @carstenartur You should never do a merge commit in a PR. You need to instead do a rebase on up to date master. You need to locally do a hard reset to the commit before the merge, then do a rebase on top of up to date master, then do a force push to fix this.

![IMG_8844](https://github.com/user-attachments/assets/f1551635-2ad6-4eca-85d7-f862ed9fc152)
This usually heals the issue

2024-09-27 18:39 UTC, carstenartur commented
> Hi @carstenartur You should never do a merge commit in a PR. You need to instead do a rebase on up to date master. You need to locally do a hard reset to the commit before the merge, then do a rebase on top of up to date master, then do a force push to fix this.

![IMG_8845](https://github.com/user-attachments/assets/1b90f9ce-8c77-44b7-8d86-568286c1153d)
Usually the „allow merge commits“ featue could simply be unchecked in the project configuration for jdt.ui to not have that accidently. But of course I know nothing about the policy for that in jdt.

2024-09-27 20:54 UTC, jjohnstn commented
Hi @carstenartur There has been discussion about why the merge is offered and I don't believe it can be done.  I am guessing it is due to some github lack of function (I also preferred gerrit).  If the rebase fixes it great, otherwise, you will have to do stuff on your local system because github lacks a lot of git functionality.

2024-09-29 19:21 UTC, carstenartur commented
> General comments.
> 
> 1. new plug-ins need about.html files (added to sources as well) - won't matter if you move them to existing plug-ins

I removed the extra plugin projects. So this time I do not try to port the code coverage computation from my sandbox project.

> 2. new plug-ins should be 1.0.0 rather than match platform 4.34 (jdt.ui and jdt.ui.tests for example are lower versions) - again moot if you move into existing test plug-ins

so this is no longer needed.

> 3. nearly all files including test sources and property files should have licensing headers (see other JDT plug-ins if in doubt)

have to check that…

> 4. plug-in name and provider name should be supplied by plugin.properties file - moot  when moved

no longer needed

> 5. remove commented out code bits unless they will be added at a later date

sure

> 6. not sure about how this is added to Java Feature tab - there are Java 10 and 18 specific items but you only add Java 6 options and this appears after Java 5 and not between 5 and 7 (should it just be on or off in a different tab like code style?)

Yes, I agree. Maybe on the tab for cleanups that might chane behavior - not really sure about this.

> 7. last encoding option has no preview changes (as far as I can see - single constant) and isn't very clear (is it needed or should it be defaulted)?

I have to find out how to consolidate all occurences of the encodings inserted into one constant per project. That was what I wanted because in my use cases that was what I needed most of the time. 

> 8. perhaps a little more description in feature option could help users to understanding what it is doing

yes, thats true. I‘ll try to improve that but don‘t hold your breath:)

2024-10-17 22:25 UTC, jjohnstn approved these changes

2024-10-17 22:53 UTC, jjohnstn commented
Hi @carstenartur I can't seem to get the JarExportTests to run successfully in the build.  They run fine locally.  They also run fine in other PRs so it doesn't seem to be a random failure.  @akurtakov Any ideas?

2024-10-18 00:49 UTC, carstenartur commented
Hi @jjohnstn, thanks for your help so far! However I tend to think that I should fix all five issues listed at the end of the description of this pr in one or another way before merge. However, you are welcome if you want to advise for one of these issues.

2024-10-18 15:36 UTC, jjohnstn commented
> Hi @jjohnstn, thanks for your help so far! However I tend to think that I should fix all five issues listed at the end of the description of this pr in one or another way before merge. However, you are welcome if you want to advise for one of these issues.

Ok, we'll try for M3, but I prefer to have such a large patch in by M1.  I still want to know why these tests are failing for this PR but not others I have built lately.  Usually, such a persistent error appears in other places at least randomly.

2024-10-18 15:39 UTC, carstenartur commented
We can add it to M1 of next release. I don't care.

2024-10-18 18:21 UTC, carstenartur commented
@jjohnstn do you think a junit 4 to junit 5 migration cleanup could be accepted even if it never will be perfect? Imho sometimes to have at least something is better than nothing.
https://github.com/carstenartur/sandbox/pull/110

2024-11-09 17:50 UTC, carstenartur commented
> Hi @carstenartur I can't seem to get the JarExportTests to run successfully in the build.  They run fine locally.  They also run fine in other PRs so it doesn't seem to be a random failure.  @akurtakov Any ideas?

I changed it to no longer being based on Java 1.5 but instead uses Java 1.8 now, not sure why this makes a difference though. Unfortunately there is a new issue with the assist for switch. Did not really look into it but just added @Ignore to the corresponding test. This one is unrelated to the code in this pr. It is the same problem on all builds.

2024-12-03 20:51 UTC, jjohnstn commented
Hi @carstenartur Could you handle the one API error for your code?  The others indicating difference in .class files I am not sure why they occur but I got them for a PR that didn't touch that code at all.  Could you also revisit my original comments some of which you had mentioned that you would look into and give a status update since you have made numerous commits after?  If the PR isn't complete, just let me know.  I would like to try to get it in for 4.35 M1.

2025-01-25 06:07 UTC, carstenartur commented
> General comments.
> 
> 
> 
> 1. new plug-ins need about.html files (added to sources as well) - won't matter if you move them to existing plug-ins

No new plugin any more
> 
> 2. new plug-ins should be 1.0.0 rather than match platform 4.34 (jdt.ui and jdt.ui.tests for example are lower versions) - again moot if you move into existing test plug-ins

No new plugin any more
> 
> 3. nearly all files including test sources and property files should have licensing headers (see other JDT plug-ins if in doubt)

Should be fine now
> 
> 4. plug-in name and provider name should be supplied by plugin.properties file - moot  when moved
No new plugin any more

> 
> 5. remove commented out code bits unless they will be added at a later date

Hope I catched all cases

> 
> 6. not sure about how this is added to Java Feature tab - there are Java 10 and 18 specific items but you only add Java 6 options and this appears after Java 5 and not between 5 and 7 (should it just be on or off in a different tab like code style?)

Not sure about the best choice here

> 
> 7. last encoding option has no preview changes (as far as I can see - single constant) and isn't very clear (is it needed or should it be defaulted)?

Should be clearer now

> 
> 8. perhaps a little more description in feature option could help users to understanding what it is doing

Hope that makes more sense now

2025-01-25 08:40 UTC, carstenartur commented
@jjohnstn could you add the helpwanted flag? Maybe somebody feels like looking into fixing the nls-comments issue mentioned in the last but one comment. Hopefully this can be prepared for the 2025-06 release.

2025-03-21 20:56 UTC, jjohnstn commented
> @jjohnstn could you add the helpwanted flag? Maybe somebody feels like looking into fixing the nls-comments issue mentioned in the last but one comment. Hopefully this can be prepared for the 2025-06 release.

If the NLS comment removal is performed, will that make it ready for review/merging?  If so, I can do it.

2025-03-22 08:30 UTC, carstenartur commented
> > @jjohnstn could you add the helpwanted flag? Maybe somebody feels like looking into fixing the nls-comments issue mentioned in the last but one comment. Hopefully this can be prepared for the 2025-06 release.
> 
> 
> 
> If the NLS comment removal is performed, will that make it ready for review/merging?  If so, I can do it.

The description contains the following remarks:

******snip*******
There are still some missing parts:

Now using a Java 22 test environment since there is no Java 18 test enviroment support in jdt ui. Should be fine.
In a number of cases the UnsupportedEncodingException is removed now. Several classes behave different. So there is no common approach to treat the situation.
The code for PrintWriter,FileReader should be reimplemented in the way the other cleanups do it
3 different options are supported "KEEP" , "USE_UTF8" ,"USE_UTF8_AGGREGATE"
KEEP means that the current behavior of the code is not changed
USE_UTF-8 means that in all cases where there is no fixed encoding we add a charset UTF-8
USE_UTF-8_AGGREGATE means the same as USE_UTF-8 but additionally add a constant to the class and refers to it
NLS Comments are currently not removed
This cleanup appears on the code style page although only using the first choice allows to keep the current behavior!
*******snap*******


So if you can solve the nls issue and can live with the other points I'm fine with merging it. In case you think 
"3. The code for PrintWriter,FileReader should be reimplemented in the way the other cleanups do it"
cannot be accepted we should be fine to comment the enum in the list and its setup in settings of the cleanup for now.
My fear is more that you come to another conclusion how the options should be implemented if at all. So just have a look and tell me what you think.

2025-04-26 00:52 UTC, jjohnstn commented
Hi @carstenartur I found out a way to remove the NLS comments that was already in ASTNodes.  I tried it out for a String explicit cleanup and it worked great.  I replaced everywhere you had removeNLS() calls and ultimately removed the removeNLS() method that I am assuming you couldn't get to work as the rewriter isn't set up to accept text edits.  You would probably have to let the rewriter form its change and then add a text edit after that.  Some tests should be added.  I am guessing that should be enough to get the patch into M2.

2025-04-30 02:44 UTC, jjohnstn requested changes
Hi @carstenartur I found a few issues I think should be cleaned up before merging into the delayed M2.  If you are too busy, I can make the changes.

2025-04-30 02:44 UTC, jjohnstn commented on org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiFixMessages.properties
> +ExplicitEncodingCleanUp_description=Set explicit encoding or default encoding where applicable on methods ''{0}'' using {1}
This message is too long in the configure cleanups view.  Drop the list of methods.

2025-04-30 02:44 UTC, jjohnstn commented on org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.properties
> +JavaFeatureTabPage_RadioName_Aggregate_to_UTF8=Insert/replace to make use of UTF-8 instead of platform encoding.\n Try to use single constant per project.
I would suggest dropping the third option with the constant.  It looks messy in the cleanup configuration dialog and unless I am missing something, IMO, offers little benefit from the 2nd option to Insert/replace to make use of UTF-8.  If you want, just remove the radio button for now and if desired, it can be added in the future.

2025-04-30 05:21 UTC, carstenartur commented
Hi @jjohnstn,please do so.

2025-04-30 19:36 UTC, jjohnstn approved these changes

2025-04-30 19:36 UTC, jjohnstn commented on org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.properties
> +JavaFeatureTabPage_RadioName_Aggregate_to_UTF8=Insert/replace to make use of UTF-8 instead of platform encoding.\n Try to use single constant per project.
Done

2025-04-30 19:36 UTC, jjohnstn commented on org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiFixMessages.properties
> +ExplicitEncodingCleanUp_description=Set explicit encoding or default encoding where applicable on methods ''{0}'' using {1}
Done

2025-05-01 16:03 UTC, jjohnstn commented
/rebase

2025-05-01 17:34 UTC, merged

2025-05-02 04:58 UTC, iloveeclipse commented
This pr most likely caused https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2196.
Please check.

2025-05-02 09:01 UTC, carstenartur commented
I don't see the connection right now but I don't have access to an ide so maybe it is just me.

I can see something like this though:

org.eclipse.jdt.testplugin.JavaProjectHelper.emptyDisplayLoop(JavaProjectHelper.java:1215)
	at org.eclipse.jdt.testplugin.JavaProjectHelper.delete(JavaProjectHelper.java:562)
	at org.eclipse.jdt.ui.tests.core.CodeFormatterTest.tearDown(CodeFormatterTest.java:83)

https://download.eclipse.org/eclipse/downloads/drops4/I20250501-1800/testresults/ep436I-unit-linux-x86_64-java21_linux.gtk.x86_64_21/org.eclipse.jdt.ui.tests.AutomatedSuite.txt

As I am unable to react the whole weekend: @jjohnstn in case you agree there is an issue could you do the rollback?

2025-05-02 20:29 UTC, jjohnstn commented
I don't see why it is causing problems, but to be safe I am going to revert for M2.  I was able to run the new testsuites that were added, successfully.

2025-05-03 14:20 UTC, iloveeclipse commented
> I don't see the connection right now

See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2196#issuecomment-2848647946