Move filters Button in Call Hierarchy view to the top level Bar
eclipse-jdt/eclipse.jdt.ui pull request #1671
Opened 2024-09-25 08:50 UTC by jannisCode

## What it does
Before the changes the filters could only be accessed through the "View Menu" (three dots), which is inconvenient considering that the filters button is rather important and frequently used.
After the changes the filters can be accessed by clicking on the icon in the top level bar as well as the old way through the view menu.

## Before
![image](https://github.com/user-attachments/assets/d3cee259-fe69-4d4a-bbab-bb1f94a7b396)
## After
![Ticket1_bearbeitet](https://github.com/user-attachments/assets/a29e5298-3283-4e7e-89da-baf7ab4c0179)

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2024-09-25 11:16 UTC, fedejeanne requested changes
@jannisCode thank you for the contribution, it looks good and works as expected!

I have some minor change requests though, mostly regarding new lines but the important one is about extracting the internal class `org.eclipse.jdt.internal.ui.callhierarchy.CallHierarchyFiltersActionGroup.ShowFilterDialogAction` in order to reduce code duplication.

2024-09-25 11:16 UTC, fedejeanne commented on org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyViewPart.java
> +
Remove empty line

2024-09-25 13:27 UTC, fedejeanne requested changes

2024-09-25 13:27 UTC, fedejeanne commented on org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyFiltersActionGroup.java
> -    // ---------- dialog related code ----------
No need to remove this line

2024-09-25 13:27 UTC, fedejeanne commented on org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/ShowFilterDialogAction.java
> +		PlatformUI.getWorkbench().getHelpSystem().setHelp(this, IJavaHelpContextIds.CALL_HIERARCHY_REFRESH_VIEW_ACTION);
Remove this

2024-09-25 13:27 UTC, fedejeanne commented on org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/ShowFilterDialogAction.java
> +		setToolTipText(CallHierarchyMessages.ShowFilterDialogAction_text);
The tooltip should only be added to the button in the bar, not to the menu. Add a new parameter called `tooltipText` and pass `null` as a value when instantiating this action from the menu,

2024-09-25 13:27 UTC, fedejeanne commented on org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/ShowFilterDialogAction.java
> +class ShowFilterDialogAction extends Action {
On a second thought, rename this one to `ShowCallHierarchyFilterDialogAction`. The reason is that by moving this class out of its previous container class (`CallHierarchyFiltersActionGroup`) the name of the action is too generic (if you look for the **type** (`Ctrl` + `Shift` + `t`) `ShowFilterDialogAction` then you'll see that there are other 2 internal classes with that name.

2024-09-27 11:37 UTC, Wittmaxi approved these changes

2024-10-01 10:07 UTC, fedejeanne commented
@jannisCode regarding this build error:
```
10:45:23  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:4.0.9:validate-version (default-validate-version) on project org.eclipse.jdt.ui: Unqualified OSGi version 3.33.200.qualifier must match unqualified Maven version 3.33.100-SNAPSHOT for SNAPSHOT builds -> [Help 1]
10:45:23  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:4.0.9:validate-version (default-validate-version) on project org.eclipse.jdt.ui: Unqualified OSGi version 3.33.200.qualifier must match unqualified Maven version 3.33.100-SNAPSHOT for SNAPSHOT builds
```

It seems that the `pom.xml` of `org.eclipse.jdt.ui` also has to be updated (increase the version too). Please do it as part of the same commit were you bumped the `MANIFEST.MF` (amend).

2024-10-02 07:02 UTC, fedejeanne approved these changes

2024-10-02 07:06 UTC, fedejeanne commented
Thank you for addressing my change request @jannisCode . The PR looks good for me but since I'm not a committer, I can't merge it. 

Maybe some committer wants to take a look and let the workflows run before reviewing/merging?

2024-10-02 19:53 UTC, vogella commented
@fedejeanne I'm not a JDT committer

2024-10-04 16:59 UTC, jjohnstn commented
@fedejeanne I'll look at it today.

2024-10-04 20:00 UTC, jjohnstn approved these changes
Looks good (all of @fedejeanne comments have been addressed) and works fine.

2024-10-04 20:04 UTC, merged

2024-10-04 20:05 UTC, jjohnstn commented
Hi @jannisCode Thank you for the patch.

2024-10-05 09:39 UTC, merks commented
@jjohnstn  @jannisCode 

After a pull, my IDE now has this error:

![image](https://github.com/user-attachments/assets/5c5b2acf-fec1-4527-9960-e415aa5d7699)

Indeed it was incremented 4 weeks ago:

![image](https://github.com/user-attachments/assets/152fa48d-18b1-46b7-88a4-e1b1b34f8fbf)

I don't think we can undo the damage after this has been pulled into an I-Build.

2024-10-07 07:28 UTC, fedejeanne commented
@merks thank you for reporting it. Do you know why was this not reported by the (GH) builds?

I noticed the same error locally when trying to fix the build in this PR but I thought it might be a false positive in my IDE. Increasing the version fixed the PR-builds. More details in my discussion (I'd like to continue the discussion there): https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/discussions/2406