Fixdeprecations
eclipse-jdt/eclipse.jdt.ui pull request #1686
Opened 2024-09-29 10:25 UTC by carstenartur

## What it does
Fix some deprecations by doing what the deprecation message suggests.

## How to test
Ideally nothing should change in behavior.

## Author checklist

- [ ] I have thoroughly tested my changes
- [X] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [X] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2024-10-03 13:07 UTC, carstenartur commented
Hi @jjohnstn , when you find the time could you have a look? While we reduced the amount of warnings with the last patch by half we are still one of the projects with the highest amount of deprecations. If you are unsure about one or another change feel free to leave it out this time.
![image](https://github.com/user-attachments/assets/798679c3-e847-4e41-b4ae-8ef3523bc3c0)

2024-10-03 15:30 UTC, jjohnstn commented
Hi @carstenartur Will look at it today.

2024-10-04 02:11 UTC, jjohnstn requested changes

2024-10-06 09:52 UTC, carstenartur commented on org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/JavaManipulationPlugin.java
> +		bundles = fBundleContext.getBundles();
As I failed to find official Update documentation I removed it.

2024-10-17 18:28 UTC, merged

2024-10-20 18:09 UTC, akurtakov commented
Would you guys please the failures at check https://download.eclipse.org/eclipse/downloads/drops4/I20241020-0600/testresults/html/org.eclipse.pde.ui.tests_ep434I-unit-cen64-gtk3-java23_linux.gtk.x86_64_23.html ? They started to appear after this change and I haven't noticed any other change in this area.

2024-10-20 19:38 UTC, carstenartur commented
Just from looking at the code 
right now I cannot see where the issue is. Can someone rollback and maybe next Weekend I can have a look?

2024-10-21 07:19 UTC, akurtakov commented
Looks like it has different cause as explained in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3125#issuecomment-2425807445