add custom folding regions
eclipse-jdt/eclipse.jdt.ui pull request #1825
Opened 2024-12-02 23:27 UTC by danthe1st

## What it does
This PR allows to add custom folding regions using comments.

I added new options to the preferences in `Java` > `Editor` > `Folding`:
![image](https://github.com/user-attachments/assets/7c208efa-f1bf-40fd-aef2-ac98c83435f9)

If a comment containing the start region and a comment containing the end region are present in the same source file, a folding region is added allowing to collapse that section. 

![image](https://github.com/user-attachments/assets/afece0bf-a700-459a-8cce-2519e3a5d28c)
![image](https://github.com/user-attachments/assets/1960653b-fc2d-4487-b645-fa78f06992c2)
![image](https://github.com/user-attachments/assets/7442dc0a-034c-41cb-bd09-12a3f89097cc)

This works even for element

## How to test
- Create a Java source file
- Create a comment containing the text `#region`
- Create a comment containing the text `#endregion`
- 

## Author checklist

- [X] I have thoroughly tested my changes
- [X] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [X] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2024-12-03 00:01 UTC, danthe1st commented
Are the CI failures due to me bumping the minor version? Should I do that differently?

2024-12-07 16:13 UTC, HannesWell commented
@fedejeanne in the dev-call on Thursday you mentioned that you could have a look at this, does this still stand?
Eventueally we need a JDT committer to submit this anyways.

2024-12-16 08:54 UTC, danthe1st commented
@jukzi Would you mind taking a look at my PR and giving feedback?

2024-12-16 13:18 UTC, fedejeanne commented
Hi. It's on my list but I am currently focusing on issues regarding the Edge browser, which have top priority until the end of the year. 
I haven't forgotten about you @danthe1st though, I am just swamped 😓

2024-12-19 09:17 UTC, fedejeanne reviewed
I did a quick review and made some comments regarding coding style.

I also tested a bit and this is what I found:
- It doesn't work if I define a region completely inside the `public static void main(String... args)` method but it does work on other methods like `public boolean equals(Object obj)`
- I can define regions if the comment **starts with** the custom text _e.g._ `// #region2`, if that is intended then the text in the preferences should say so. I would add some extra label explaining how custom regions work, right before the 2 check-boxes
- If I fold the `// #region2` in this snippet, the `System.out.println()` is folded too:

```java
@Override
public boolean equals(Object obj) {
	// #region1
	// #region2
	if (this == obj)
		return true;
	if (obj == null || getClass() != obj.getClass())
		return false;
	Cat cat = (Cat) obj;
	// #endregion2
	System.out.println();
	return size == cat.size;
	// #endregion1
}
```
- Moving regions around works without reopening the source file but **creating** regions doesn't. I would very much like it to work too, it doesn't feel natural to have to close the editor to add regions.


## Your questions

> Custom folding regions are disabled if either of the custom texts/preferences are empty or if one contains the other. Should I add some information about that to the preferences? Would it be better to disable it by default (currently, it defaults to #region/#endregion)?

Some info about it is supposed to work is good but I'd keep it short, 2-3 lines in a label. If it gets too long you could consider adding some help page like the [Readme example](https://github.com/user-attachments/assets/574b8cc5-3214-42ca-972f-3724cdd17623) does.
I'd disable (gray out) the **group** "Custom folding regions" in the preferences if the **checkbox** "Custom folding regions" is not selected.

> I haven't written any tests so far. Are there existing tests for folding in JDT-UI? What about performance tests (my implementation requires scanning more parts of the source file which could affect performance)?

To test performance you'll have to do it manually. Alter this generator (credits to Andrey Loskutov) and let it generate several internal classes with custom folding regions: [GenerateJava.zip](https://github.com/user-attachments/files/18195150/GenerateJava.zip). Then sample with VisualVM and share the results.

I don't know of any functional tests, maybe someone else does?

> Regarding performance, I used String#contains to check whether comments contain certain the region begin/end tokens (e.g. #region/#endregion) which requires creating a String for each comment every time the file is edited. Should I change that to use the char[] returned by getCurrentTokenSource() or similar?

You'll have to sample with VisualVM and see if this is a performance bottle-neck.

> I have bumped the minor version of org.eclipse.jdt.ui due to adding new elements in PreferenceConstants. Is this ok that way?

It's fine and this commit did the same so you're safe: d0563dcb67679ab00626ff63283f5bceb5d0ea54. Such bumps are no longer necessary since they will be done automatically by GH, as was the case for the mentioned commit.

> I guess this should be added to the "New and noteworthy" list (assuming this change gets accepted and merged). If so, should I add it and is [this](https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/4.35/jdt.html) the right place?

Correct, but let's cross that bridge when we get there :-) . Usually a committer adds the "noteworthy" tag to your PR / Issue right after it was merged/solved and that's your queue to do the PR for the N&N entry.

2024-12-19 14:30 UTC, danthe1st commented
> It doesn't work if I define a region completely inside the public static void main(String... args) method but it does work on other methods like public boolean equals(Object obj)

Should be fixed, this was because of it being the only (or last) method.

> I can define regions if the comment starts with the custom text e.g. `// #region2`

It should work whenever a comment includes the text `#region` so it could be `// Hello #region World` or anything like that. If you would (intuitively) expect something else, I'd be happy to hear that and possibly change my implementation. Currently, it treats all comments the same way but I'm open to change that if other people prefer it differently.

> Moving regions around works without reopening the source file but creating regions doesn't. I would very much like it to work too, it doesn't feel natural to have to close the editor to add regions.

Interestingly, that worked for my by just adding a comment like `// #region` or whatever. What doesn't work is it being automatically updated when changing the preferences related to custom folding regions.

> I'd disable (gray out) the group "Custom folding regions" in the preferences if the checkbox "Custom folding regions" is not selected.

> I don't know of any functional tests, maybe someone else does?

I didn't find any existing tests related to folding so I'll try making my own tests for custom folding regions in a new directory `org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/folding` (I currently don't have a _good_ way to access the folding regions/annotations added to the editor and I don't want to add API just for tests but I might find a good way to do it at some point ()). If anyone still finds tests after that, it shouldn't be hard to move them (once I wrote the tests).

My current approach for automated tests is subclassing `DefaultJavaFoldingStructureProvider` and overriding `computeFoldingStructure` and `getProjectionRanges` to access the created `IRegion[]`s.

2024-12-19 14:41 UTC, danthe1st commented
![image](https://github.com/user-attachments/assets/4e852690-05c7-4605-b276-9a5b07b33d64)

2024-12-19 15:43 UTC, BeckerWdf commented
The texts: "Text marking start of custom folding region" looks a bit unnecessary too long for my
Why not simply saying "Text marking start of region" and "Text marking end of region"
due to the box around you don't need to repeat that it's a "custom folding region".

I am unsure if it's singular "region" or pluar "regions".

2024-12-19 17:42 UTC, danthe1st commented
As discussed in today's devcall, I changed the PR to disallow regions between an element and it's child.
```java
class X{
	// #region
	void a() {
		// #endregion this is not folded with the outer region because it is at a different level
		
		// #region However, this is folded because loops are not considered children elements and I don't think it's a good idea to parse all of that for folding
		for(int i=0; i<10;i++) {
			// #endregion
		}
	}
	// #endregion this will be folded with the outer region
}
```

2024-12-19 21:57 UTC, danthe1st commented
I ran the generator mentioned by @fedejeanne with 12_000 inner classes (the default) and added a custom region both outside and inside each of these classes.

I loaded the class in Eclipse, started CPU sampling with VisualVM, added some newlines at the top, bottom and in the middle of the file. I also added a single-line comment in the middle of the file.
This is what VisualVM shows:
![image](https://github.com/user-attachments/assets/ce69c6c0-7d94-4b6d-bfb6-4d28122ee69d)

Similar with CPU profiling:
![image](https://github.com/user-attachments/assets/014b7410-61f0-4105-b071-137c5293a8c6)

As it seems, the custom folding logic does have an impact on performance.

Loading all the folding annotation takes a bit of time in general (especially with the profiler active) but it does not block the UI.


CPU profiling with similar operations _with custom folding regions disabled_:
![image](https://github.com/user-attachments/assets/27bc22be-fb2d-4a4e-9572-492f36517ef7)

2024-12-20 07:10 UTC, fedejeanne commented
@danthe1st can you provide:
1. The simplified version of the generated file (generate it with 1 inner class)
2. Sampling/performance analysis for the same scenarios on `master` (for comparison)?

Keep in mind that generating 12.000 inner classes is an extreme case so performance will always degrade, the question is _how much_.

2024-12-20 07:41 UTC, akurtakov commented
As a reference for people interested in similar functionality for other editors - Generic editor provides extension point for that https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.genericeditor/schema/foldingReconcilers.exsd

2024-12-20 09:00 UTC, danthe1st commented
profiling with merge base (not _current_ master but the master I based my PR on):
![image](https://github.com/user-attachments/assets/5a796588-8e7d-4f8d-bcf9-6d8e6e97da1b)

sampling:
![image](https://github.com/user-attachments/assets/4f98ebc5-9c85-4b11-9723-493ebdabe531)


Generated code with one inner class:
```java
package a.generated;

public class TestClass {

    // #region outside
    public static class InnerClass0 {
        // #region inside
        public int x = 42; // no error
        
        public void helloWorld() {
                System.out.println("Hello World!"); // no error
                System.out.println("In class " + 0 + ", x=" + x); // expected error
        }
        // #endregion inside
    } // end of InnerClass0
    // #endregion

}
```

2024-12-20 11:17 UTC, danthe1st commented
Other experiment with 6_000 inner classes and each class having a multiline comment with 20 lines each containing the character `a` 100 times:
```java
// #region outside
    /*
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    */
    public static class InnerClass0 {
        // #region inside
        public int x = 42; // no error
        
        public void helloWorld() {
                System.out.println("Hello World!"); // no error
                System.out.println("In class " + 0 + ", x=" + x); // expected error
        }
        // #endregion inside
    } // end of InnerClass0
    // #endregion
```

Custom regions disabled, sampling:
![image](https://github.com/user-attachments/assets/0c466c31-ffed-4ec4-9b3c-0242dcb046c3)

Custom regions disabled, profiling (I had to disable automated collapsing of normal/header comments to be able to do this without Eclipse not responding):
![image](https://github.com/user-attachments/assets/1f947eef-26d7-4d39-8713-974796b92490)

Custom regions enabled, sampling:
![image](https://github.com/user-attachments/assets/0a3947c9-4836-4a23-8a78-0ce63c1e38bd)


Custom regions enabled, profiling (automated collapsing of comments enabled as well):
![image](https://github.com/user-attachments/assets/7e69f58f-5eb7-4f1c-8b29-367ad9c8548f)

2024-12-20 12:28 UTC, danthe1st commented
I realized that I can use the information of what the current token is from the `scanner` to know where I need to start looking for characters (so I don't need to check for things like `//`). With this change, it is now required that region markers (`#region`/`#endregion`) are at the start of the comment so `// Hello #region World` is now prevented as discussed in the devcall.

2024-12-20 13:15 UTC, danthe1st commented
I noticed a bug in my implementation where the following is not detected:
```java
class Z{
	void a() {
		// #region this is not detected because there is an inner class (considered as a child) in the same scope
		int x;
		
		// #endregion
		class I{
			
		}
	}
}
```
I plan to try fixing it.

2024-12-23 08:58 UTC, BeckerWdf commented
> ![image](https://private-user-images.githubusercontent.com/34687786/397417023-4e852690-05c7-4605-b276-9a5b07b33d64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDQ0NzQsIm5iZiI6MTczNDk0NDE3NCwicGF0aCI6Ii8zNDY4Nzc4Ni8zOTc0MTcwMjMtNGU4NTI2OTAtMDVjNy00NjA1LWIyNzYtOWE1YjA3YjMzZDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA4NTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MTZhYjFhODBmMmNiYzY0YmE4OTFlNThmZDczYWE1OTg3NzUwMDIzMzMzM2NhZDU2NmJjYTc5MTRlNDk4OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W9h3TxiqLI8btZh9Vbthpn6NBSJEhmB0XedC6xk1fEg)
> 
> I might still rework that label in the future.

I am not a big fan of big explanatory text directly in the preference page. Can't we simply put this into the help document related to that preference page?

2024-12-23 08:59 UTC, BeckerWdf reviewed
Thanks for the text shortening.

2024-12-24 07:55 UTC, danthe1st commented
> I am not a big fan of big explanatory text directly in the preference page. Can't we simply put this into the help document related to that preference page?

I guess I can remove the label and write a PR changing https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/reference/preferences/java/editor/ref-preferences-folding.htm once this is done.

2024-12-25 19:51 UTC, danthe1st commented
I have drafted a PR for the help here: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2703

2024-12-25 20:08 UTC, danthe1st commented
I have squashed and rebased my PR onto the current master.

2024-12-26 17:05 UTC, danthe1st commented
Profiling results using a class containing 6000 inner classes similar to the following:
```java
    // #region outside
    /*
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    * aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    */
    public static class InnerClass0 {
        // #region inside
        public int x = 42; // no error
        
        public void helloWorld() {
                System.out.println("Hello World!"); // no error
                System.out.println("In class " + 0 + ", x=" + x); // expected error
        }
        // #endregion inside
    } // end of InnerClass0
    // #endregion
```

sampling profiling of `opening the file` shows main thread actions, `other operations after opening` shows parts of the `JavaReconciler`.

### sampling
opening the file (custom regions enabled):
![image](https://github.com/user-attachments/assets/f34fe71d-fb3b-4e84-b3ea-ead0187b6244)

opening the file (custom regions disabled):
![image](https://github.com/user-attachments/assets/5c2b8efe-bb59-4a5f-8966-18f8364a2790)

opening the file (master):
TODO


other operations after opening (custom regions enabled):
![image](https://github.com/user-attachments/assets/74ea6bb7-2315-4323-8d56-41abbe39959e)

other operations after opening (custom regions disabled):
![image](https://github.com/user-attachments/assets/73034917-e2d4-4988-a383-cedafb846b6a)

other operations after opening (master):
TODO

### profiling

opening the file (custom regions enabled):
![image](https://github.com/user-attachments/assets/6626c0e8-0a5c-487d-8821-008f9b329b03)


opening the file (custom regions disabled):
![image](https://github.com/user-attachments/assets/e25ab149-dce8-446f-a984-ece97223a3bc)


opening the file (master):
TODO


other operations after opening (custom regions enabled):
![image](https://github.com/user-attachments/assets/86109814-f3c4-435f-b780-5ca1073347b7)


other operations after opening (custom regions disabled):
![image](https://github.com/user-attachments/assets/2a27d720-a050-48f7-9fd0-288e2d7319a3)


other operations after opening (master):
TODO

2024-12-29 15:35 UTC, danthe1st commented
I want to note that I am still open to change the default region markers from `#region` and `#endregion` to `region` and `endregion` (comments would then look like `// region` and `// endregion` or similar).

2024-12-30 12:45 UTC, BeckerWdf commented
> ![image](https://private-user-images.githubusercontent.com/34687786/397417023-4e852690-05c7-4605-b276-9a5b07b33d64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NjI4OTcsIm5iZiI6MTczNTU2MjU5NywicGF0aCI6Ii8zNDY4Nzc4Ni8zOTc0MTcwMjMtNGU4NTI2OTAtMDVjNy00NjA1LWIyNzYtOWE1YjA3YjMzZDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDEyNDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YzMyZTk5N2JmNWI5MTVjYTEzMWZlOGIyYWQ3Njk3OWU4MDViNDBmZjIzMGZmMmQ1ZTA4MjRkZGVkNDBlZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DAwggtPi6iR4WNqz3kZzlDCCs8DANPVnR71c1EkTTk4)
> 
> I might still rework that label in the future.

Just another remark:
This is a workspace specific setting. Wouldn't it make sense to have that on the level of the project so that this settings are also checked into the git repo of the project? So that the folding is the same for all devs working together on the same project.

2024-12-30 19:21 UTC, danthe1st commented
> Just another remark: This is a workspace specific setting. Wouldn't it make sense to have that on the level of the project so that this settings are also checked into the git repo of the project? So that the folding is the same for all devs working together on the same project.

I guess this also makes sense to change.

2024-12-31 17:00 UTC, danthe1st commented
@BeckerWdf I have implemented project-specific preferences for folding.
If a third-party folding provider is not declaring support for per-project preferences by implementing `IScopedJavaFoldingPreferenceBlock` (an interface I created), it is displaying a message when opening the per-project preferences for that specific folding provider (this only happens when enabling project-specific settings _and_ selecting that folding provider in there).
![image](https://github.com/user-attachments/assets/a628f4da-481c-4cae-bb78-6cbe875c2e82)

2025-01-13 13:58 UTC, BeckerWdf commented
> @BeckerWdf @fedejeanne I think this PR is ready for a re-review if any of you can find the time to do it (otherwise I'm fine waiting more)

I am not a JDT committer. So I don't have the rights to approve the PR.

2025-01-15 08:53 UTC, fedejeanne commented
> > @BeckerWdf @fedejeanne I think this PR is ready for a re-review if any of you can find the time to do it (otherwise I'm fine waiting more)
> 
> I am not a JDT committer. So I don't have the rights to approve the PR.

@BeckerWdf non-committers can also approve PR's although the PR is not "_approved_" (green) so committers may miss your approval

@danthe1st I'll try to review it this week.

2025-01-17 18:49 UTC, jjohnstn commented
Hi @danthe1st without reviewing the source I have a few design comments:

1. I'm not sure using line comments is a robust solution.  The problem with line comments is that they usually get tied to statements below them.  This is a problem because cleanups or refactoring may remove a statement or move the statement.  In some cases, the comment tied to the statement is removed and in other cases the comment gets moved with the statement.  This isn't what you or the user is expecting.  Thinking about it, I think one solution is to use a block comment in an empty block.  For example:
```
    {/* folding region 1 */}
    int i = 3; // unused variable
    if (object instanceof Integer) {
       return 3;
    }
    {/* folding region 1 */}
```

In the case above, it doesn't matter if the unused variable gets removed or if any of the code block is moved because the empty blocks won't go with them or be removed themselves.  The other benefit is that this allows you to fix the name of the comment without having the user specify it.  It must be the only comment in an  empty block (no statements).  User code is never going to collide with this, especially if you give the comment a specific name.  In my example, I added numbers to do matching but you may prefer on/off or just the presence of the comment automatically toggles.  With this, no preferences for the triggers are needed as they are set in stone.  It would be nice to enhance the formatter to recognize these empty blocks and by default prevent moving the block end to the next line on a reformat.

2. Having to reopen a file is a major usability negative.  If the aforementioned idea removes the possibility of changing the marker, it is possible to simply always process.  If you need to make it optional due to poor performance, a possible solution would be to have a separate plug-in the user can install.  Otherwise, you need to find a way to reopen/reparse the file programatically.  You want the user to have the same experience as other folding.  

What do you think?

2025-01-17 19:11 UTC, danthe1st commented
1. My implementation actually allows any type of comment for this. If someone wants to use line comments, they can use line comments and if they prefer something else, they can do that. 
2. This is not really about my implementation but actually about how preferences are loaded from the `DefaultJavaFoldingStructureProvider`. This has been "fixed" in #1562.

2025-01-17 19:59 UTC, danthe1st commented
I added a test for your example (within a method):
```java
package org.example.test;
public class Test {
	void a(){
		{/* #region 1*/}
		System.out.println("Hello World");
		{/* #endregion 1*/}
	}
}
```
This example works but I won't note that using this style wouldn't work in non-local contexts because of https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1825#issuecomment-2555349388 but I think this shouldn't be much of an issue:
```java
package org.example.test;
public class Test {
	{/* #region this is not recognized*/}
	void a(){
		System.out.println("Hello World");
	}
	{/* #endregion this is not recognized*/}
}
```
```java
package org.example.test;
public class Test {
	{/* #region because things like this shouldn't be possible*/}
	void a(){
		System.out.println("Hello World");
		{/* #endregion this is not recognized*/}
	}
}
```

2025-01-22 15:50 UTC, danthe1st commented
Since this PR contains both the change adding custom folding regions and making the folding preferences project-specific (see https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1825#issuecomment-2565439652), I can split the latter off in its own PR if wanted.

2025-01-24 22:32 UTC, danthe1st commented
I have split off the part about project-specific properties from folding into #1979.

2025-01-31 21:17 UTC, danthe1st commented
I have changed the defaults to only require the text `region` instead of `#region` since I think the `#` symbol is a bit arbitrary.

2025-02-01 16:03 UTC, danthe1st commented on org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionNewFoldingTest.java
> +/*******************************************************************************
This test class runs all tests from `testCommentsInEmptyBlocks` with the new folding introduced in #1562.
The test methods that yield different results (due to the folding being different in some ways, for example #1992) are overridden.

2025-02-12 07:10 UTC, BeckerWdf commented
Just something that to my mind: Why is this feature in JDT? Isn't independent from Java and could also be implemented in Platforms "plain" text editor?

2025-02-12 08:02 UTC, danthe1st commented
> Just something that to my mind: Why is this feature in JDT? Isn't independent from Java and could also be implemented in Platforms "plain" text editor?

JDT uses its own logic for folding already so I think implementing it somewhere else would result in it not being usable within the Java editor.

2025-02-12 17:36 UTC, jjohnstn requested changes
Overall works quite well.  I noticed an issue with having a unended region start in a block which paired up with another endregion outside of the block.  I had a statement in the block (e.g. local variable declaration).  I wanted it to be only if the block has no statements (only comments).  If that is too hard to implement quickly then drop the block suggestion for now.

The preferences for region start should be brought up under the Custom Folding enablement button and indented.  They should read:

Region start comment text
Region end comment text

That way it is clear that it only applies to comments.  I like that you can have text after the comment so you can tag your regions (since you only see the region start comment when folded).

I will start to review the actual code immediately.   I would suggest you work on the above UI changes right away.  Understandably my code comments might not apply after your next round of changes but simply mark them as resolved since they are no longer relevant.  The cut-off for M3 is tomorrow at 5:00 so I'd like to try and get it in by then otherwise we have to wait until 4.36 M1.

2025-02-12 17:57 UTC, jjohnstn commented
> @jjohnstn Would you care to review the code at some point since you also reviewed other recent folding-related PRs?

Sure. 

> Overall works quite well. I noticed an issue with having a unended region start in a block which paired up with another endregion outside of the block. I had a statement in the block (e.g. local variable declaration). I wanted it to be only if the block has no statements (only comments). If that is too hard to implement quickly then drop the block suggestion for now.
> 

Hmm, some more testing.  It appears the regions start and ends are allowed to cross block boundaries if not properly nested.  End region can be in an inner block or an outer block to the start region comment.  So I guess if the behavior is documented, it should be ok for now.

2025-02-12 20:59 UTC, jjohnstn commented on org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionNewFoldingTest.java
> +		FoldingTestUtils.assertContainsRegionUsingStartAndEndLine(projectionRanges, str, 4, 8);//void a()
Why isn't the void a() method region 4, 9?

2025-02-12 20:59 UTC, jjohnstn commented on org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionNewFoldingTest.java
> +		FoldingTestUtils.assertContainsRegionUsingStartAndEndLine(projectionRanges, str, 3, 10);//void a()
Again, I am confused on the end line value.  I assume you will clarify why the end-line matches the endregion comment for custom regions but the end brace line is not part of a method fold.

2025-02-12 20:59 UTC, jjohnstn commented on org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
> +	private boolean fCustomFoldingRegionsEnabled= true;
Curious why this isn't false by default, but perhaps it will make sense later on.

2025-02-12 22:08 UTC, jjohnstn requested changes
In my test, I turned off custom folding, but it did not remove the folding markers and they continue to work.

2025-02-13 10:18 UTC, danthe1st commented on org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionNewFoldingTest.java
> +		FoldingTestUtils.assertContainsRegionUsingStartAndEndLine(projectionRanges, str, 4, 8);//void a()
## TL;DR

If you have a method, showing the `}` when folding the method is wanted but with custom regions, there isn't much of a point in including the `// endregion` comment.

For the `CustomFoldingRegionTest`, it works differently due to #1825.

The main purpose of these tests is to check that the custom regions are working correctly so I wrote them to check against how it works in the repository so I am using the folding from master and add my own regions to it to check whether everything is folded correctly.

## Background

This is #1992 and these tests are how I discovered that issue. When a folding region is present before a method (e.g. a multiline comment or a custom region) and the "new" folding is disabled, the last line (`}`) is collapsed with the folding region.
With the new folding, this is not the case so the region ends one line earlier.

You can observe the behavior without my PR
```java
public class Test {
	/**
	 * 
	 */
	void a(){
		System.out.println("Hello World");
	}
}
```
When the `a()` method is folded, the `}` is hidden (by folding) if and only if the "Activate feature" option is disabled in the "Extended Folding" group.

2025-02-13 10:23 UTC, danthe1st commented on org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionNewFoldingTest.java
> +		FoldingTestUtils.assertContainsRegionUsingStartAndEndLine(projectionRanges, str, 3, 10);//void a()
Again, showing the `}` makes sense for folded methods and was added by jakub-suliga's changes.

For custom folding regions, there is no point in showing the `// endregion` comment.

If the behavior of including the `// endregion` line is wanted, I can add that.

2025-02-13 10:33 UTC, danthe1st commented on org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
> +	private boolean fCustomFoldingRegionsEnabled= true;
I just followed using the defaults in the method above. This shouldn't make much of a difference since it should be set by `initializePreferences()` but I guess it's better to be `false` since `fCustomFoldingRegionBegin` and `fCustomFoldingRegionEnd` are not initialized (fixed).

2025-02-13 18:34 UTC, jjohnstn commented
> > In my test, I turned off custom folding, but it did not remove the folding markers and they continue to work.
> 
> How did you turn it off? Note that the "Custom folding regions" checkbox is in the "Initially fold these elements" group and does not configure whether folding of custom regions is enabled. When I turn off custom region folding by clearing the text in one of the text fields in the "Custom folding regions" group, the folding regions disappear for me.
> 
> If the UX is confusing, I guess an option would be to add a checkbox to the "Custom folding regions" group about enabling/disabling it?

My bad.  The other items don't disable unless you disable all folding.

2025-02-13 18:46 UTC, jjohnstn commented on org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionNewFoldingTest.java
> +		FoldingTestUtils.assertContainsRegionUsingStartAndEndLine(projectionRanges, str, 3, 10);//void a()
Ok.  Thanks for the explanation.  It works fine in usage.

2025-02-13 18:47 UTC, jjohnstn commented on org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionNewFoldingTest.java
> +		FoldingTestUtils.assertContainsRegionUsingStartAndEndLine(projectionRanges, str, 4, 8);//void a()
Thanks.  Consider it resolved.

2025-02-13 18:48 UTC, jjohnstn commented
So, just the UX concerns remain.  The movement of the comment text inputs under Custom folding (indented) and the wording of the text fields.  Other than that, I think it is ready to merge.

2025-02-13 18:54 UTC, danthe1st commented
>  The movement of the comment text inputs under Custom folding (indented)

What exactly do you mean with that? Does that refer to the decision on whether the `// endregion` comment should be folded or not?

> wording of the text fields

I assume you are talking about whether to use `region` or `#region` as the default?

2025-02-13 19:59 UTC, jjohnstn commented
The strings above are for the description of the text fields for the region markers (not the text inside the fields).

2025-02-13 21:21 UTC, danthe1st commented
> I think that having the text fields in the top group right by the Custom folding checkbox is clearer.

Is there any reason for this? The top group is for _initially folding_ elements so I don't think adding extra configuration for custom folding regions there makes sense. The only thing these checkboxes are changing is whether these entries are collapsed or expanded by default.

>  I want the strings to read "Region start comment text" and "Region end comment text" which tells the user it is a comment.

Done

![image](https://github.com/user-attachments/assets/3f3eb760-5976-4d23-983a-e3bed8c894ac)

2025-02-13 21:48 UTC, jjohnstn commented
> > I think that having the text fields in the top group right by the Custom folding checkbox is clearer.
> 
> Is there any reason for this? The top group is for _initially folding_ elements so I don't think adding extra configuration for custom folding regions there makes sense. The only thing these checkboxes are changing is whether these entries are collapsed or expanded by default. The name `EDITOR_FOLDING_CUSTOM_REGIONS` should probably be `EDITOR_FOLDING_COLLAPSE_CUSTOM_REGIONS` or similar (I went with a name corresponding to the existing similar names).
> 

It is much cleaner. - one less group in the dialog.  The settings are only relevant to the custom folding checkbox so putting them there (indented) doesn't require the user to look elsewhere.   I am not a fan of the added group for the extended folding and eventually this should be merged above unless the individual items are broken out.

2025-02-13 21:50 UTC, danthe1st commented
Also note that currently, my tests use the current behavior from master which does not include the fixes from #2014 and #2015. Merging this PR will make #2014 and #2015 fail but fixing it should be very easy (they should just not be merged concurrently).

2025-02-13 22:15 UTC, danthe1st commented
> It is much cleaner. - one less group in the dialog. The settings are only relevant to the custom folding checkbox so putting them there (indented) doesn't require the user to look elsewhere. I am not a fan of the added group for the extended folding and eventually this should be merged above unless the individual items are broken out.

In that case, I guess it would be best to rename the existing group since the name "Initially fold these elements" would no longer be fitting (and custom folding regions also make sense to be used if that checkbox is disabled).

2025-02-13 22:24 UTC, danthe1st commented
Also, do you have any opinion on adding an additional checkbox for enabling/disabling folding as opposed to just letting users disabling by clearing out the Region start comment text/Region end comment text?

2025-02-13 22:25 UTC, jjohnstn commented
> > It is much cleaner. - one less group in the dialog. The settings are only relevant to the custom folding checkbox so putting them there (indented) doesn't require the user to look elsewhere. I am not a fan of the added group for the extended folding and eventually this should be merged above unless the individual items are broken out.
> 
> In that case, I guess it would be best to rename the existing group since the name "Initially fold these elements" would no longer be fitting (and custom folding regions also make sense to be used if that checkbox is disabled).
> 
> That being said, I could imagine not using groups for custom folding regions at all.

Not sure what you mean about the group name being inappropriate.  Are you are referring to the fact that the custom folding is regenerated if the text fields change so not truly initially at startup?  BTW: I merged those PRs you mentioned #2014 and #2015 as they were bug fixes that should have already been merged so thanks for the reminder about them.

2025-02-13 22:33 UTC, danthe1st commented
> Not sure what you mean about the group name being inappropriate.

The current preference screen looks like this:
![image](https://github.com/user-attachments/assets/4eb28031-b529-48f5-a8ea-764fcaa27835)

I am assuming you are talking about the "Initially fold these elements" group. which contains a "Custom region folding" checkbox.

None of the checkboxes in that group enable or disable the addition of folding annotations at any point. The only difference these checkboxes make is whether these are collapsed by default or not.

If I enable all checkboxes in that group, it looks like this:
![image](https://github.com/user-attachments/assets/2fc1e43c-69db-4a82-8d03-47a15f0c1426)

If I disable all of them, I get the following:
![image](https://github.com/user-attachments/assets/2dcb370d-6f8a-4cfd-a6c9-5cde8c12c783)

As you can see, the folding regions are added/processed either way. It's just that enabling these checkboxes collapses some parts when a file is opened. By default, this is the case for imports and header comments since once typically doesn't want to see those.

2025-02-13 22:48 UTC, danthe1st commented
> BTW: I merged those PRs you mentioned https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2014 and https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2015 as they were bug fixes that should have already been merged so thanks for the reminder about them.

I rebased my changes and adapted my tests to no longer use the special cases/behavior that should be fixed by these PRs.

2025-02-13 23:06 UTC, jjohnstn commented
Ok, I wasn't thinking clearly,  Yes, I see what you mean now.  I think that adding the enablement button makes sense.

2025-02-13 23:47 UTC, danthe1st commented
> I think that adding the enablement button makes sense.

I added it.

2025-02-14 00:42 UTC, jjohnstn approved these changes

2025-02-14 00:47 UTC, jjohnstn commented
@danthe1st Works great.  One more change is needed - the default for the enablement should be false.  Any new feature should do this.

2025-02-14 00:51 UTC, danthe1st commented
> @danthe1st Works great. One more change is needed - the default for the enablement should be false. Any new feature should do this.

Done

2025-02-14 01:34 UTC, jjohnstn commented
Thanks @danthe1st

2025-02-14 19:16 UTC, jjohnstn commented
Hi @danthe1st I will try and merge the patch as soon as 4.36 M1 opens up.  RC1 is next week and RC2 the following week after that.

2025-02-15 22:50 UTC, fedejeanne commented
> Looking at #2019, I used the same approach for the tests introduced with this PR ensuring I only need one test class.
> 
> @fedejeanne Should I add you in the copyright notice?

No need, but thank you for asking :-)

2025-03-02 15:26 UTC, danthe1st commented
I noticed that the line containing `void test(){}` would be folded in the following code:
```java
package org.example.test;

public class Test {
	// region

	/* endregion */ void test(){}
}
```
I changed it so that the last line is not included if there's other text in that line.

2025-03-06 21:49 UTC, jjohnstn commented
Hi @danthe1st.  Is this done?  I am not going to review it if you are going to make further changes.  I would like to get it into 4.36 M1 and then you can tweak it if you like once people have a chance to try it and perhaps open issues as needed.

2025-03-06 22:25 UTC, danthe1st commented
> Hi @danthe1st. Is this done? I am not going to review it if you are going to make further changes. I would like to get it into 4.36 M1 and then you can tweak it if you like once people have a chance to try it and perhaps open issues as needed.

Yes, I consider it done. I just bumped the version of `org.eclipse.jdt.ui` to `3.35.0` in order to make the build pass.

2025-03-07 01:55 UTC, merged

2025-03-07 01:55 UTC, jjohnstn commented
Thanks @danthe1st