Improve the Safety of Extract Local Variable Refactorings concering ClassCasts #331
eclipse-jdt/eclipse.jdt.ui pull request #333
Opened 2022-11-14 16:53 UTC by chixiaye

**This is a patch based on the solution explained in the bug report.**
The main changed file is `Checker.java`, the description of the modification of this file is as follows:

## 1. Implement Void ClassCasts Exception
Compared with the solution proposed in the original issue, we apply a more generalized solution. First, we traverse the selected expression and create a mapping from expression to type for each `CastExpression`. Second, we validate the code snippet between the variable declaration and the first expression matching the selected expression. If we detect the `InstanceofExpression` and value corresponding to the key value, `leftOperand` of  `InstanceofExpression`, is equal to the `rightOperand` of  `InstanceofExpression` or its supertype, we would assert that such extracting is unsafe.

## 2. Refactoring
Considering this class not only aims at avoiding NullPointerException but also ClassCastExecption, we renamed it to `Check` and renamed the inner class `NullMiddleCodeVisitor` to `MiddleCodeVisitor`. Besides, we removed some private fields of the inner classes to make the code more concise.

2022-11-30 22:32 UTC, jjohnstn requested changes
Looks good but a few comments to address.

2022-12-06 14:21 UTC, chixiaye commented
Hi, as you suggested, we improved the relevant code. I think the check of resolveBinding can be merged into the check that `getSuperClass()` does not return, so I did not add an extra resolveBinding check.

2022-12-10 12:53 UTC, liuhuigmail commented
@jjohnstn Please let us known if there is anything deserving further improvement.  Thank you.

2022-12-12 18:50 UTC, jjohnstn commented
@liuhuigmail Will look at it today or tomorrow.  I was on vacation last week and will be on vacation from Dec 19th onward.

2022-12-14 22:23 UTC, jjohnstn commented
Hi, everything looks good except you haven't fixed hasInheritanceRelationship() to handle interfaces.  For example, you could have:

public interface A {
    public int getInt();
}

public class B implements A {
    public int getInt() {
       return 7;
    }
}

public class C {
    public void foo(Object obj) {
        if ((obj instanceof A) && ((A)obj).getInt() > 3) {
           ....
        }
   }
}

If an instance of B is passed to C.foo() and the user asks to put the 2nd part of the if statement in a local variable,
your logic for hasInheritanceRelationship() won't catch it because getSuperClass() only finds those types specified
in an "extends" clause, but not an "implements" clause so you will never find a match with interface A.  There is a separate call for getting interfaces getInterfaces() that needs to be called in addition to getSuperClass() and you should make the method recursive.  Essentially you can check the passed in class and all of its interfaces, then recursively call for each of the interfaces and with the super class if it exists.   This will ensure you check the whole inheritance tree.  Each recursive call can check if you get a match and stop the recursion.

2022-12-14 22:40 UTC, jjohnstn commented
@chixiaye BTW: I added a N&N entry for your previous null check fix in 2022-12 and it made the release video:
https://youtu.be/jJau4kUoLrA

2022-12-15 02:55 UTC, liuhuigmail commented
@jjohnstn  Thank you for the comments. We will fix it quickly and resubmit the patch.  
By the way, we have submitted another issue concering the Extract Local Varialbe refactoring (https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/348). Would you please kindly have a look and let us known whether it is ok for us to prepare a patch (pull request)  as we specified in the issue report.  Thanks.

2022-12-17 13:11 UTC, chixiaye commented
Hi, the method `hasInheritanceRelationship` has been improved to identify the inheritance concerning the interface. And the implementation of `hasInheritanceRelationship` has also been changed to a recursive form. Besides, Test-128 and Test-129 were added to verify the inheritance relationship between classes and interfaces. Test-130 and Test-131 were added to test the inheritance relationship between interfaces.

2023-01-06 21:21 UTC, jjohnstn approved these changes

2023-01-06 21:34 UTC, jjohnstn approved these changes
Looks good.  Just need to get build working.

2023-01-06 23:15 UTC, jjohnstn commented
Hi @chixiaye, please look at the results of the latest build.  There is a warning and the build is failing due to -failonwarning being specified.  It is complaining about using int as a key for a Map.

2023-01-09 19:23 UTC, merged