Migrate to javax.servlet.jsp-api from Maven-Central
eclipse-jdt/eclipse.jdt.ui pull request #343
Opened 2022-12-09 23:27 UTC by HannesWell

Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/748

And apply some minor code enhancements.

2022-12-12 20:10 UTC, jjohnstn requested changes
Looks good, but you should bump the versions of the two plug-ins changed.

2022-12-13 07:58 UTC, HannesWell commented
> Looks good, but you should bump the versions of the two plug-ins changed.

Thanks for reviewing. Just did the bump.

2022-12-13 15:47 UTC, jjohnstn approved these changes

2022-12-13 15:47 UTC, merged

2022-12-13 15:47 UTC, jjohnstn commented
Thanks Hannes.