Fix NPE in AbstractJavaCompletionProposal
eclipse-jdt/eclipse.jdt.ui pull request #556
Opened 2023-05-01 14:46 UTC by gzsombor

Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.text.IDocument.get(int, int)" because "document" is null
	at org.eclipse.jdt.internal.ui.text.java.AbstractJavaCompletionProposal.isAutoInsertable(AbstractJavaCompletionProposal.java:1338)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.canAutoInsert(CompletionProposalPopup.java:1624)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.lambda$0(CompletionProposalPopup.java:513)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)

## What it does

## How to test

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2023-05-02 13:27 UTC, iloveeclipse requested changes
The change itself is perfectly fine.
But may I ask you to:
1) Create a bug that describes the issue and steps to reproduce
2) Change commit message to have a proper title line and a line that includes the link to the issue? Something like this:
```
Avoid NPE in case there is no document provided by context

Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/<your issue number>
```
3) Amend commit here to have that commit message in git
4) Force push to github

2023-05-03 06:04 UTC, gzsombor commented
Unfortunately, I couldn't reproduce it - it happened once, after I've deleted a bigger code block, and clicked on undo, and on code completion. 
 I've applied your suggestions, thanks for the quick review!

2023-05-03 07:45 UTC, iloveeclipse approved these changes

2023-05-03 07:45 UTC, merged

2023-05-03 07:45 UTC, iloveeclipse commented
Thanks