Proposals branch
eclipse-jdt/eclipse.jdt.ui pull request #815
Opened 2023-09-21 20:50 UTC by robstryker

## What it does

Splits the proposal logic into core and UI. It moves the vast majority of the logic into the core classes, while maintaining the UI as existing wrappers for stability. 

This patch also creates an IInvocationContextCore class and makes it the default interface for use in the core objects, in the same way as #813 made the core classes use the relevant Core interface. Just as in the problem location situation, the UI's API interface extends the hidden non-API core one. 

This patch depends on #813  and #814 

## How to test

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2023-09-21 20:53 UTC, robstryker commented
This patch is very difficult to proof-read, due to the fact that the bulk (but not the entirety) for about 37 classes have been moved into their own new unique internal core classes. This means the vast majority of the patch is removals of 90% of one file, and creation of that same code in a new file. 

I'm not sure how to improve this patch to make it more easily followable and to verify that no logic changes have occurred hidden in the patch. =/

2023-09-22 18:23 UTC, jjohnstn commented
Hi @robstryker There are new conflicts to fix for this patch.

2023-09-22 19:59 UTC, robstryker commented
Squashed and rebased. Looking for a final green build.

2023-09-23 00:23 UTC, jjohnstn requested changes

2023-09-23 00:23 UTC, jjohnstn commented on org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/AddAllMissingJavadocTagsProposalCore.java
> +package org.eclipse.jdt.internal.ui.text.correction;
Missing license.  A few others are missing licenses as well.  Other than that, looks good.

2023-09-23 00:26 UTC, jjohnstn commented
@robstryker Please also rebase.  It would be good if you can get this in before Monday where large patches are frowned upon.

2023-09-23 01:19 UTC, jjohnstn commented
/rebase

2023-09-25 02:53 UTC, jjohnstn approved these changes

2023-09-25 03:51 UTC, jjohnstn commented
Jenkins appears to be off so new build is not occurring.  Last change built successfully and the only change since then was the addition of copyright headers done my myself.  This refactoring change should go into M1 as it is too big for M2 or M3 so I am merging this before the Monday deadline which requires no large changes.

2023-09-25 03:54 UTC, merged

2023-09-25 04:19 UTC, jjohnstn commented
@iloveeclipse please note above.